AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Messages project authentication

Parameters:
  CognitoDomain:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Enter a string. Must be alpha numeric 3-63 in length.
    Default: messages-auth
  FrontendUrl:
    Type: String
    Description: "URL of frontend CDN"


Resources:
  # --- AWS Cognito ---

  MessagesUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${CognitoDomain}-user-pool
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true

  MessagesUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${CognitoDomain}-user-pool-client
      UserPoolId: !Ref MessagesUserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref FrontendUrl
      LogoutURLs:
        - !Ref FrontendUrl
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

  MessagesUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref MessagesUserPool

Outputs:
  MessagesUserPoolArn:
    Description: ARN of Cognito UserPool
    Value: !GetAtt MessagesUserPool.Arn
    Export:
      Name: !Sub "${AWS::StackName}-user-pool-arn"
  MessagesUserPoolID:
    Value: !Ref MessagesUserPool
    Description: The UserPool ID
  MessagesAppClientID:
    Value: !Ref MessagesUserPoolClient
    Description: The app client
  MessagesUserPoolDomain:
    Value: !Ref MessagesUserPoolDomain
    Description: The UserPool domain
