name: Frontend deploy on AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: |
          aws --version
          python --version
          sam --version

      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Upload frontend
        run: |
          aws s3 sync --cache-control 'max-age=604800' frontend s3://messages-frontend-bucket/
          aws cloudfront create-invalidation --distribution-id  E28MV6ERBVKA4C --paths "/*"
